name: gasandelec
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7781
title: Gas and Electricity Testing on 0800 832 1198 in the UK
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313131'
    - '#005ba4'
    - '#ffa76d'
    - '#ddf8ff'
    - '#949693'
  brandStrength: 0.34701034403406084
  lightness: 0.592787757050246
  saturation: 0.8005491595249623
  rhythmicContrast: 0.8471624348312616
purpose: []
