typography_spectrum: 0
color:
  brandColors:
    - '#f2f2f2'
    - '#2d55b9'
    - '#af9c97'
    - '#3f231d'
    - '#a03331'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.8471624348312616
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: UA-75121389-1
  facebook: null
  twitter: null
name: gasandelec
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 797daf80-03b4-4827-bf93-4c3e7a487b65
    url: >-
      2016-03-15-gas-and-electricity-testing-on-0207-175-0060-in-london-wwwg.html
    name: Gas and Electricity Testing on 0207 175 0060 in London www.gasandelec.com
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b354dc3f-f463-4067-98b1-af7468a8f7ba.jpg
title: Gas and Electricity Testing on 0800 832 1198 in the UK www.gasandelec.com
purpose: []
